/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HPG7cuvhC5R
 */
import Link from "next/link";

import ShoppingBagIcon from "@/components/icon/ShoppingBagIcon";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const CheckoutSuccessMessage = () => {
  return (
    <Card className="w-full max-w-sm mx-auto shadow-none">
      <CardContent className="flex flex-col items-center space-y-4 pt-6">
        <ShoppingBagIcon className="h-8 w-8" />
        <div className="text-center font-bold text-xl">
          Thanks for your order!
        </div>
        <div className="text-sm text-center text-gray-400">
          Your order has been confirmed and will be processed soon.
        </div>

        <Button asChild className="w-3/4 mx-auto">
          <Link href="/" replace>
            Back
          </Link>
        </Button>
      </CardContent>
    </Card>
  );
};

export default CheckoutSuccessMessage;
